### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'foundation-datetimepicker'

### ISSUE THREAD

**Issue by hackeron** [aliibrahim/foundation-datetimepicker-rails#14]
Seems there is a problem with version 0.2.0.

```
$ bundle exec rake assets:precompile                       
rake aborted!
Sprockets::FileNotFound: couldn't find file 'foundation-datetimepicker'
  (in /Users/Hackeron/Development/Xanview/timeline/app/assets/javascripts/application.js:23)
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:106:in `resolve'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:146:in `require_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:217:in `process_require_directive'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:167:in `block in process_directives'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:165:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:165:in `process_directives'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:99:in `evaluate'
/usr/local/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:37:in `init_with'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/asset.rb:24:in `from_hash'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:54:in `cache_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:257:in `benchmark'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:210:in `find_asset'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:119:in `block in compile'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `compile'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/usr/local/lib/ruby/gems/2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

As a temporary solution I downgraded to foundation-datetimepicker-rails = 0.1.3 :(

Any ideas why this is happening? - any solution?

**Comment by aliibrahim** [comment]
Hi @hackeron Thanks for pointing this out. The following issue has been resolved now. Please download the latest version of gem which is 0.2.1 now and you should not face any problems.
